#!/bin/sh
##########################################################################
##                                                                      ##
## copies the kernel to the right place                                 ##
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. ./config_build
. "$SCRIPTS"/misc/lib/lib_fail

echo "Copying kernel ....            "

cp "$KERNEL"/vmlinuz "$ROOTFS"/isolinux/vmlinuz || fail

echo
