#!/bin/bash
# shellcheck disable=SC2004,SC2009,SC2068,SC2002
# shellcheck disable=SC1091

if [ $(($TESTME)) -gt 0 ] ; then
    .  ./preinit.sh
else
    .  /sbin/preinit.sh
fi

SDCOM="/var/tmp/.shutdowncmd"

# Bye Bye root
NEWHOME="/home/user"
mkdir -p $NEWHOME

# Xorg needs these
export XAUTHORITY=$NEWHOME/.Xauthority
export ICEAUTHORITY=$NEWHOME/.ICEauthority

while : ; do
    rm -f $SDCOM                # Fresh start
    getargy 'bsleep' && sleep "$FOUNDVAL"

    getargx 'initbreak=pre-gui' && tmpshell  "$FOUNDVAR $ "

    # Start Xorg as a regular user
    su - user -c "./.startup.sh"
    chvt 1

    # Here one can examine post - gui
    getargx 'initbreak=post-gui' &&  tmpshell "$FOUNDVAR $ "

    # Shutdown?
    if [ -e $SDCOM ] ; then
        shutdownx
    fi

    # If it got here, it is a logout or shutdown error
    #echo "Exit this shell to continue."
    tmpshell "XFCE loop iteration $ "
    #export PS1="Comlin Post GUI \w$ $ " ; setsid -c -w /bin/bash

done

# Can not reach this ... just in case

# Start a shell for recovery / diagnosis
export PS1="Comlin PreInit fallback: \w $ "
while : ; do
   echo "Spawning new shell $$ \w # "
   setsid -c -w /bin/bash
   sleep 1
done

# EOF
