#!/bin/bash
# shellcheck disable=SC1091,SC2010

# Set the TESTME variable to non zero if you are in a sim / test environment.
# Warning: script tests will not work in the real env.
#TESTME=1

# Silence async messages on terminal
/usr/bin/setterm --msg off

# Silence comments and commands on terminal
#set +x; set +v

export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin"
export LC_ALL=en_US.UTF-8

# ------------------------------------------------------------------------
# Ended up with ONE separate file. (for unit tests and shellcheck):

if [ $((TESTME)) -gt 0 ] ; then
    .  ./preinit.sh
    .  ./terminit.sh
else
    .  /sbin/preinit.sh
    .  /sbin/terminit.sh
fi

# If we are in ISO (read only) mode, change permissions

PPP=$(ls -ld /root/ | grep rw)
if [ "$PPP" == "" ] ; then
    loginfo 0 "Changing permissions."

    chmod -R u+w /root/.
    chmod -R u+w /home/user/.
    chown -R user.users /home/user/.
    chmod -R u+w /home/guest/.
    chown -R guest.users /home/guest/.

    chmod -R a+rw /run
    mkdir -p /run/user
    chown -R user.users /run/user/.

    chmod -R a+rwt /tmp

    setsuids
fi

# Tell the kernel
mount  -o remount,rw /

# Variables:
#    verbose=lev        Verbosity level
#    isleep=sec         Sleep after commands for visual observation
#    ibreak=when        Break for shell
# There are several break items, see source below (ibreak)

# History:  Tue 14.Jan.2025     Sound works, created /dev entries by hand
#           Sat 15.Feb.2025     Restructure /proc ... etc to --bind
#           Sat 15.Feb.2025     Writable media
#           Thu 01.May.2025     The read only chmod corrected

# Determine overall flags for operation
getargy 'verbose' && export VERBOSE=$FOUNDVAL

loginfo 1 "Preinit stage ..."

#loginfo 0 -n "Booting Community Linux, Lib version: $LIBVERS "
#echo -e " \033[32;1mOK\033[0m"

# Patch some basic environment vars
export TERM=linux
export HOME=/root
export USER=root
export TMP=/tmp
export TEMP=/tmp
export RUN=/run

cd $HOME || echo "Warn:" cannot cd to $HOME >&2

mkdir -p /var/tmp
mkdir -p "$SUL"

# Create for log append, add current date value to the beginning
DDD=$(date)
echo "$DDD" > "$SULOUT" ; echo "$DDD" > "$SULERR"

getargy 'verbose' && export VERBOSE=$FOUNDVAL
getargx 'ibreak=all' && export BREAKALL=1

# Do not leave us hanging without a name
hostname "$(cat /etc/hostname)"  >>"$SULOUT" 2>>"$SULERR"
domainname "$(cat /etc/domainname)"  >>"$SULOUT" 2>>"$SULERR"

[ -e /dev/console ] || ln -s /dev/tty0 /dev/console

# This was a bad idea ... too much crap is included
#sysctl --system

# Install devices from PCI bus(es)
getargx 'ibreak=devices' && tmpshell "$FOUNDVAR $ "
devload "Detecting devices ... "
getargy 'isleep' && sleep "$FOUNDVAL"

# Install modules specified by the user's /etc
getargx 'ibreak=modules' && tmpshell "$FOUNDVAR $ "
loginfo 0 -n "Installing modules ... "
loadmods
getargy 'isleep' && sleep "$FOUNDVAL"
echo -e " \033[32;1mOK\033[0m"

# Virtual terminals and a serial port
getargx 'ibreak=pre-vt' && tmpshell "$FOUNDVAR $ "
loginfo 0 -n "Starting VTs ... "
startvts
getargy 'isleep' && sleep "$FOUNDVAL"
echo -e " \033[32;1mOK\033[0m"

# Second round for dependents (like: WIFI)
devload "Loading devices ... "

#loginfo 1 "Created mounts."

# Time to find the writable disk
getargx 'ibreak=pre-hd' && tmpshell "$FOUNDVAR $ "

NEWROOT=/newroot; mkdir -p $NEWROOT
HDROOT="/hdroot"; mkdir -p $HDROOT

MOUNT_DISK="" ; FSCK=""

getargy 'nodisk' && export NODISK=$FOUNDVAL

if [ "$NODISK" != "" ] ; then
    echo  "Starting without writable DATA media. " #Enter key to continue. "
    #read -r
    #sleep 2
    bindall /
    # User wants no data mount
    setsid /sbin/postinit
    exit
fi

# Make the clear data command's name a non obvious one

# Used to be clear-data ... but I kept typing clean.. delete nails it.
getargy 'delete-data'  && export CLEARDATA=$FOUNDVAL
getargy 'delete-disk'  && export CLEARDISK=$FOUNDVAL

getargy 'fsck'   && export FSCK=$FOUNDVAL

# Find and mount available writable media
getargx 'ibreak=findhd' && tmpshell "$FOUNDVAR $ "
findHD $HDROOT

if [ "$CLEARDATA" != "" ] ; then
    echo "About to delete ALL files from data storage ... ";
    if [ "$MOUNT_DISK" == "" ] ; then
        echo "No data to clear ... "; sleep 2
    else
        prompt "Are you sure you want to clear all DATA? (yes/no) "
        if [ "$?" == "1" ] ; then
            echo "Checking ... $MOUNT_DISK"
            fsck -y "$MOUNT_DISK"

            mount "$MOUNT_DISK" "$HDROOT"
            echo -e " \033[32;1mOK\033[0m"
            echo "Clearing ... $HDROOT"
            rm -rf "$HDROOT/fs/*"
            rm -rf "$HDROOT/work/*"
            umount "$HDROOT"
            echo -e " \033[32;1mOK\033[0m"
        fi
    fi
fi

if [ "$CLEARDISK" != "" ] ; then
    echo "About to DELETE Data Device ... "
    echo "Warning: this option is mainly for development / testing."
    prompt "Are you sure you want to clear data DISK? yes/no "
    if [ "$?" == "1" ] ; then
        if [ "$MOUNT_DISK" == "" ] ; then
            echo "No disk to clear"; sleep 2
        else
            PARTX=$(echo "$MOUNT_DISK" | awk '{ printf("%s", substr($1, 0, length($1)-1) ); }')
            PARTNUM=$(echo "$MOUNT_DISK" | awk '{ printf("%s", substr($1, length($1)) ); }')
            echo "Clearing part $PARTX partnum $PARTNUM"
            sfdisk "$PARTX" --delete "$PARTNUM"
            sync ; partprobe "$PARTX"
            findHD "$HDROOT"
            getargx 'ibreak=post-del' && tmpshell "$FOUNDVAR $ "
        fi
    fi
fi

if [ "$MOUNT_DISK" == "" ] ; then
    # No DATA FS found, do FS creation or ram disk
    #prompt "Cannot find data storage. Search free space for autocreate ? (yes/no) "
    keypeek "No R/W storage. Search free space for autocreate ? (y/n/ret/esc) "
    if [ "$?" == "1" ] ; then
        echo "Auto creating space for data." ; sleep 1
        DEVF=$(sfdisk -F | grep Unpartitioned | awk '{print $3;}' | head -1 | tr -d ":")
        echo "Found space: \"$DEVF\" "
        if [ "$DEVF" == "" ] ; then
            echo "No free space found. Starting in nosave mode."
            echo -n "Press Enter to continue ... "
            read -r
            setsid /sbin/postinit
            exit
        fi
        OUTF=$(echo ,,, | sfdisk -a --no-reread "$DEVF" | grep "new partition" \
                | awk '{print $1;}' | head -1 | tr -d ":")
        if [ "$OUTF" == "" ] ; then
            echo "Could not create partition. Starting in nosave mode."
            sleep 2
            setsid /sbin/postinit
            exit
        fi
        #echo "Created $OUTF"
        sync ; partprobe "$DEVF"
        getargx 'ibreak=pre-format' && tmpshell "$FOUNDVAR $ "
        mkfs.ext2 -F "$OUTF"  || (echo "Error on mkfs"; sleep 2)
        mount "$OUTF" "$HDROOT"  || (echo "Error on mount"; sleep2)
        touch  "$HDROOT/$COMLIN_DATAFILE" # Mark volume
        umount $HDROOT
        findHD $HDROOT
        getargx 'ibreak=post-create' && tmpshell "$FOUNDVAR $ "
        if [ "$MOUNT_DISK" == "" ] ; then
            echo "Failed auto creating space for data. Starting in nosave mode."
            sleep 2
            setsid /sbin/postinit
            exit
        fi
    else
        loginfo 0 "Started without writable media."
        setsid /sbin/postinit
        exit
    fi
fi

loginfo 0 -n "Data storage at '$MOUNT_DISK' ... "
echo -e "\033[32;1mOK\033[0m"

loginfo 0 -n "Starting file system checks ... "

if [ "$FSCK" != "" ] ;  then
    # Forced check
    fsck -f -y "$MOUNT_DISK"
else
    # Silent check
    fsck -T -y "$MOUNT_DISK" >>"$SULOUT" 2>>"$SULERR"
fi

getargy 'isleep' && sleep "$FOUNDVAL"
echo -e " \033[32;1mOK\033[0m"

getargx 'ibreak=pre-mount' && tmpshell "$FOUNDVAR $ "
mount  "$MOUNT_DISK" "$HDROOT"
getargy 'isleep' && sleep "$FOUNDVAL"

mkdir -p $HDROOT/fs ; mkdir -p $HDROOT/work

# Done here, mount overlay
getargx 'ibreak=pre-overlay' && tmpshell "$FOUNDVAR $ "
mount -t overlay  comlin_data  \
    -olowerdir=/,upperdir=$HDROOT/fs,workdir=$HDROOT/work,redirect_dir=nofollow \
     $NEWROOT
getargy 'isleep' && sleep "$FOUNDVAL"

# Clear environment of generated vars
unset  FOUNDVAL FOUNDVAR FOUNDCMD
unset  MOUNT_DISK MOUNT_DATA SUL
unset  CLEARDISK CLEARDATA LIBVERS

bindall $NEWROOT

cd "$NEWROOT" || echo "Cannot CD to $NEWROOT"

getargx 'ibreak=pre-chroot' && tmpshell "$FOUNDVAR $ "

post_chroot

# EOF
