#
# We created two excutables, following Linux tradition. In the origianl
# implementation, these are symlinks to one excutable, but we are keeping it simple.
#

all: notify

notify: notify.c
	gcc notify.c -ldl -o notify

