#!/bin/sh
##########################################################################
##                                                                      ##
## assembles the gzipped initrd image                                   ##
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. ./config_build
. "$SCRIPTS"/misc/lib/lib_fail

echo "Assembling initrd .... "

# // Create zeroed image file and make a filesystem

dd if=/dev/zero bs=1k count="$RAMSIZE" > "$TMPDIR"/initrdfs || fail
mke2fs -F -i1024 -m0 -b1024 "$TMPDIR"/initrdfs || fail
tune2fs -c0 -i0 "$TMPDIR"/initrdfs || fail

# // Mount it on $MOUNTPOINT
mount -o loop "$TMPDIR"/initrdfs "$MOUNTPOINT" || fail

# // We don't need that
rmdir "$MOUNTPOINT"/lost+found

# // Copy initrdfs onto initrdfs image

echo -n "Copying initrd fs to "$TMPDIR"/initrdfs ... "
cp -dpR "$INITRDFS"/* "$MOUNTPOINT" || fail
echo "Done"

# // Umount initrdfs
umount "$MOUNTPOINT"

# and gzip it
echo -n "gzipping "$TMPDIR"/initrdfs ... "
    gzip -9 "$TMPDIR"/initrdfs || fail
echo "Done"

# Move the initrdfs to its final destination
mv "$TMPDIR"/initrdfs.gz "$ROOTFS"/isolinux

echo

