#!/bin/bash

if [ "$1" != "justvars" ] ; then
    check_drive ../config_drive
fi

IMGFILE="32G.img"
INSTROOT="$GRUBROOTp"2
INSTARG="/mnt/guest"
ISOFILE="../../comlin64.iso"
TMPSYS="../../_system"
ISOMNT="/mnt/iso"
GRUBDATA="/mnt/data"
GRUBSTORE="/mnt/store"
COMLIN_DATAFILE=.comlin_data

if [ ! -e $GRUBROOT ] ; then
    echo echo $0: Please plugin $GRUBROOT
    exit 1
fi

if [ "$1" == "justvars" ] ; then
    #echo Jus export vars, no checks
    return
fi

ALREADY=$(mount | grep $INSTROOT)
if [ "$ALREADY" ==  "" ] ; then
    echo $0: Not mounted $GRUBROOT
    exit 1
fi

# More checks
if [ ! -e data/grub.cfg ] ; then
    echo echo $0: Must start from grub-data dir
    exit 1
fi

# EOF
