#!/bin/bash
###############################################################################
##                                                                           ##
##                            make_toritoimage                               ##
##                                                                           ##
## This script takes the directory structure of _initrdfs/ (which represents ##
## the initial ramdisk initrd), gzips it and copies it on a floppy disk      ##
## mage. Then it prepares grub and writes the floppy image to                ##
## $ROOTFS/boot/boot.img.                                                    ##
## The Floppy image should then be a fully functional el torito boot image.  ##                                                                  ##
## The recipe to integrate grub into the set is heavily based on             ##
## information provided to me by Petr Konecny <pekon@informatics.muni.cz>.   ##
##                                                                           ##
## This program is free software; you can redistribute it and/or modify      ##
## it under the terms of the GNU General Public License as published by      ##
## the Free Software Foundation; either version 2 of the License, or         ##
## (at your option) any later version.                                       ##
##                                                                           ##
###############################################################################

. config_build

#. "$SCRIPTS"/misc/lib/lib_fail

fail() {
    echo "Failed " $1 $2
}

cleanup() {

    sudo umount $MOUNTPOINT
    sudo losetup -d $LODEV

    rm -f $TMPFILE
}

echo "----------------------------------"
echo "    creating boot floppy image    "
echo "               grub               "
echo "----------------------------------"
echo
echo

if [ ! -f $KERNEL/vmlinuz ] ; then
    echo "Please execute 'make getkern' first."
    exit 1
fi

TMPFILE=$TMPDIR/tmpfile
dd if=/dev/zero of=$TMPFILE bs=512 count=100000
LODEV=$(losetup -f)
sudo losetup $LODEV $TMPFILE || fail
mkfs.ext4 $LODEV

sudo grub-install  $LODEV

sudo mount $LODEV $MOUNTPOINT || fail

mkdir -p $MOUNTPOINT/grub

if [ "$CRAMFS" = "yes" ]; then
	cat "$SCRIPTS"/misc/files/grub_menu.lst          \
		| sed "s|RAMSIZE|$RAMSIZE|;s|CRAMFS|cramfs|" \
		> $MOUNTPOINT/grub/menu.lst
else
	cat "$SCRIPTS"/misc/files/grub_menu.lst    \
		| sed "s|RAMSIZE|$RAMSIZE|;s|CRAMFS||" \
		> $MOUNTPOINT/grub/menu.lst
fi

# copy kernel onto grubfs image
cp "$KERNEL"/vmlinuz $MOUNTPOINT || fail copy

# copy memtest86 image onto grubfs image
cp "$SCRIPTS"/misc/files/memtest86.bin $MOUNTPOINT/memtest.86 || fail memtest

# move compressed initrdfs onto lilofs image
#mv $TMPDIR/initrdfs.gz $MOUNTPOINT || fail move

#cleanup

#exit


# move grubfs image to BURN_THIS/boot/boot.img
#mv $TMPDIR/grubfs $ROOTFS/boot/boot.img

# EOF
