#!/bin/sh
##------------------------------------------------------------------------
##
## Copies USB drive to USB image
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
##------------------------------------------------------------------------

. ./config_build

. "$SCRIPTS"/misc/lib/lib_fail

echo
echo "----------------------------------"
echo " Copying boot items               "
echo "----------------------------------"
echo

mkdir -p _boot/boot
sudo cp -a ./boot/* _boot/boot

echo Done.
sync

