#!/bin/bash
##########################################################################
##                                                                      ##
## Make the install ISO                                                 ##
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. config_build
. "$SCRIPTS"/misc/lib/lib_fail

echo "----------------------------------"
echo "        Making ISO image          "
echo "----------------------------------"
echo

## if we use a compressed ISO9660 image we need the -z switch
#if [ "$COMPRESSEDFS" = "yes" ]; then
#    Z="-z"
#fi

mkdir -p $ROOTFS
mkdir -p $ROOTFS/boot

#rm -rf $ROOTFS/boot/*
#cp $SCRIPTS/misc/files/memtest86.bin $ROOTFS

echo -n "Copying filesystem ... "
#rsync -ahu --progress ../comlin-usb-000/* $ROOTFS
cp -a $LITEUSB/* $ROOTFS
echo OK

echo -n "Copying boot items ... "
cp -r $KERNELDIR/* $ROOTFS/boot
cp -r $BOOT/* $ROOTFS/boot
echo OK

touch  $ROOTFS/COMBOOT

#chown -R $USER $ROOTFS

echo -n "Making ISO ... $ROOTISOFILE"
mkisofs -input-charset utf-8 -R -b boot/grub/stage2_eltorito -no-emul-boot  \
         -boot-load-size 4 -boot-info-table -o $ROOTISOFILE \
         -quiet $ROOTFS  || fail
echo
stat -c "ISO written, %s bytes." $ROOTISOFILE
echo Done
