#!/bin/sh
##------------------------------------------------------------------------
##
## Copies USB drive to USB image
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
##------------------------------------------------------------------------

. ./config_build

. "$SCRIPTS"/misc/lib/lib_fail

TARG=/media/COMBOOT
MCOMBOOT=/media/COMBOOT

echo
echo "----------------------------------"
echo " Copying Minimal files            "
echo " May need sudo pass ..."
echo "----------------------------------"
echo

if [ ! -d _work ] ; then
  echo  "Must start from project root (comlin-xxx)"
  exit
fi

#echo "Copying minimal system to $LITEUSB ... (may take a while)"
echo -n "Copying lite to $LITEUSB ... "

# Just in case
mkdir -p $LITEUSB

DIRS="dev mnt bin sbin usr usr/bin usr/local boot etc opt media run var \
lib var/lib"

# Lets create basic dirs
for ii in $DIRS; do
    mkdir -p $LITEUSB/$ii
done

FILES="sh cp mv gunzip gzip umount mount cat dd \
rmdir tar"

# Some minimal files
for iii in $FILES; do
    cp /bin/$iii $LITEUSB/bin/
done

#mke2fs tune2fs
cp $INITDIR/init $LITEUSB/sbin
chmod a+x $LITEUSB/sbin/init

#echo "You may want to disable power save for the duration of the copy."

echo Done.
#sync

