#!/bin/bash
##########################################################################
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

echo "----------------------------------"
echo "Making / Burning img to USB drive "
echo "----------------------------------"

# See if conditions are met (checks are also in prepiso)

if [ ! -f $KEYGET ] ; then
    echo "Execute 'make apps' first."
    exit 1
fi

if [ ! -f $KERNELDIR/$KERNELBIN ] ; then
    echo "Execute 'make getkern' first."
    exit 1
fi

if [ ! -f $KERNELDIR/initramfs ] ; then
    echo "Execute 'make initramfs' first."
    exit 1
fi

if [ ! -f ./boot/grub/grub.cfg ] ; then
    echo "Execute 'make getboot' first."
    exit 1
fi

# Do we have an ISO?
if [ ! -f ./boot/grub/grub.cfg ] ; then
    echo "Execute 'make buildiso' first."
    exit 1
fi

# See if we have a good target

if [ ! -f ./config_drive ] ; then
	echo "USB drive not configured yet. Run 'make detect' first"
	exit 1;
fi
read -r RRR < config_drive

DDD=$(echo $RRR | awk -F "=" '{print $2}')

MMM=$(mount | grep $DDD)
if [ "$MMM" != "" ] ; then
    echo "Drive $DDD is mounted, exiting."
    exit 1
fi

if [ ! -e $DDD ] ; then
    echo Drive \'$DDD\' does not exist
    exit 1
fi
echo Configured drive is: \'$DDD\'
make buildiso2
cd grub-data ; ./do_cd.sh

# EOF
