#!/bin/sh
##########################################################################
##                                                                      ##
## assembles the gzipped initrd image                                   ##
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. ./config_build
. "$SCRIPTS"/misc/lib/lib_fail

SINK=/dev/null

echo "----------------------------------"
echo "        Assembling initrd         "
echo "        May need sudo pass        "
echo "----------------------------------"
echo 

# Create zeroed image file and make a filesystem
echo Creating ${RAMSIZE}k bytes holder file ...
dd if=/dev/zero bs=1k count=$RAMSIZE > $TMPDIR/initrdfs 2>/dev/null || fail

echo Creating holder FS ...
#mke2fs -F -i1024 -m0 -b1024 "$TMPDIR"/initrdfs 2>&1 >$SINK || fail
mke2fs -F "$TMPDIR"/initrdfs 2>&1 >$SINK || fail
tune2fs -c0 -i0 "$TMPDIR"/initrdfs  2>&1 >$SINK || fail

# Mount it on $MOUNTPOINT
sudo mount -o loop "$TMPDIR"/initrdfs "$MOUNTPOINT" || fail

# we don't need that
sudo rmdir "$MOUNTPOINT"/lost+found

# copy initrdfs onto initrdfs image
echo -n "Copying initrd fs to "$TMPDIR"/initrdfs ... "
sudo cp -dpR "$INITRDFS"/* "$MOUNTPOINT" 

echo "Copying utilities"
sudo cp  -v  reboot/linux_reboot "$MOUNTPOINT"/sbin
sudo cp  -v  reboot/linux_poweroff "$MOUNTPOINT"/sbin
sudo cp  -v  keyget/keyget "$MOUNTPOINT"/bin

# Make sure it is owned by root
sudo chown -R root.root $MOUNTPOINT

echo "Done copying"
df $MOUNTPOINT

#echo Examine FS ... ### Testing ###
#bash

sudo umount "$MOUNTPOINT"
sudo losetup -d /dev/loop0

# Not needed (PG)
#sudo losetup -d /dev/loop1

# Gzip it
echo -n "Gzipping "$TMPDIR"/initrdfs ... "
gzip -9f "$TMPDIR"/initrdfs || fail
echo "Done gzipping"

#ls -l "$TMPDIR"/initrdfs*


