#!/bin/bash

. ./config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

#echo "-------------------------------------"
#echo " Get apps into new image "
#echo "-------------------------------------"

if [ ! -f $KEYGET ] ; then
    echo "Please exceute 'make apps' first."
    exit 1;
fi

mkdir -p $ROOTFS/bin
echo -n "Copying APPS ... "

cp $APPDIR/keyget/keyget $ROOTFS/bin
cp $APPDIR/reboot/linux_reboot $ROOTFS/bin
cp $APPDIR/reboot/linux_poweroff $ROOTFS/bin
cp $APPDIR/MessageBox-X11/progress $ROOTFS/bin
cp $APPDIR/pypass/passcheck $ROOTFS/usr/bin

cp -au $APPDIR/pangview $ROOTFS/root/Utils
cp -au $APPDIR/pyedpro  $ROOTFS/root/Utils

echo OK

# EOF

