#!/bin/sh
##------------------------------------------------------------------------
##                              
## Creates a drive image on USB 
##                                                                      
## This program is free software; you can redistribute it and/or modify 
## it under the terms of the GNU General Public License as published by 
## the Free Software Foundation; either version 2 of the License, or    
## (at your option) any later version.                                  
##                                                                      
##------------------------------------------------------------------------

. ./config_build
. "$SCRIPTS"/misc/lib/lib_fail

TARG=/media/COMBOOT
copyDir() {
	echo Copying $1 to  $TARG
 	[ -d $TARG/$1 ] || mkdir -p $TARG/$1
	cp -au $1/* $TARG/$1
}

echo
echo "----------------------------------"
echo " Copying image to USB  "
echo " May need sudo pass ..."
echo "----------------------------------"
echo 

# Is the drive here?
GREPX=`mount | grep $DDEV`

if [ x"$GREPX" == x"" ] ; then 
    echo Mounting $DDEV
	echo "Mount (insert) $DDEV first."
   	exit
fi

# Is the second drive here?
GREPX=`mount | grep $DDEV2`

if [ x"$GREPX" == x"" ] ; then 
    echo Mounting $DDEV
	echo "Mount (insert) $DDEV2 first."
   	exit
fi

echo "Copying system ...  (may take a while)"
	
copyDir /sbin
copyDir /bin
copyDir /lib
copyDir /etc
copyDir /usr
copyDir /var/lib

# Special case
echo Creating var and subs ...
sudo mkdir -p /media/COMBOOT/var
sudo mkdir -p /media/COMBOOT/var/log
sudo mkdir -p /media/COMBOOT/var/run

echo Done.
sync

