#!/bin/sh
##------------------------------------------------------------------------
##
## Cleans local USB image from pipes sockets
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
##------------------------------------------------------------------------

. ./config_build  nocheck
. "$SCRIPTS"/misc/lib/lib_fail

echo
echo "----------------------------------"
echo " Clean USB images "
echo " May need sudo pass ..."
echo "----------------------------------"
echo

rm -rf $CURRUSB/*
rm -rf $LITEUSB/*

sync


