#!/bin/bash

echo -n "Remove the USB Drive (if inserted), and then press the Enter key ...  "
read

lsblk | grep "^[a-z]" > aa

echo -n "Insert the target USB drive, and then press the Enter key ...  "
read

echo -n "OK, testing for new mount ... "
sleep 2
echo

lsblk | grep "^[a-z]"  >bb

DD=`diff aa bb`
#echo $DD

EE=`echo $DD | awk  '{ print $3 };' | sed  s/[0-9]// `
#echo $EE

if [ "" != "$EE" ] ; then
	echo Detected USB drive in /dev/$EE
	# Create configuration entry
    echo "# Drive configured by 'make detect'" > config_drive
    echo "RDDEV=/dev/$EE" >> config_drive
    echo "# EOF" >> config_drive
else
	echo "No Drive detected, please try again"
    echo "# No Drive detected" > config_drive
fi

rm -f aa bb
chown $SUDO_USER config_drive

# EOF