#!/bin/bash
# shellcheck disable=SC1091

. ./config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

echo
echo "------------------------------------- "
echo " Getting initramfs files from system  "
echo "--------------------------------------"
echo

REALROOT=/
OUTDIR=./test_init
MLIST=scripts/initram_modules.txt

FROM=6.8.0-59-generic
OUTDIR=test_init

# Calc array size
NUM=$((${#INITRAMFSDIRs[@]}-1))

for AA in $(seq 0 $NUM)  ; do

    DDD=${INITRAMFSDIRs[$AA]}
    SSS=${INITRAMFSSUBs[$AA]}
    echo Processing: $DDD
    #echo Subst: $SSS

    mkdir -p $DDD

    # Copy original files
    cp -au initramfs/initramfs.org/* $DDD

    # Copy module files from runtime
    while read -r AA  ; do
        FF=""
        AA=$(echo -e $AA"\n"| sed s/^\.//)
        FFF=$(echo $AA | grep $FROM)  # ; echo $FFF
        if [ "$FFF" == "" ] ; then
            continue
        fi
        BB=$(echo $AA | sed s/$FROM/$SSS/)
        if [ -d $BB ] ; then
            # Do not copy dirs
            #echo skipping dir: $BB
            continue
        fi
        DD=$(dirname $BB)
        if [ ! -d  $DDD$DD ] ; then
            #echo mkdir -p $DDD$DD
            mkdir -p $DDD$DD
            true
        fi
        # Silence missing modules (from older kernel)
        if [ -f $BB ] ; then
            #echo cp -a $BB $DDD
            cp -a $BB $DDD$DD
        fi
    done < $MLIST
done

# EOF
