#!/bin/sh
##------------------------------------------------------------------------
##                              
## Copies USB image to USB drive
##                                                                      
## This program is free software; you can redistribute it and/or modify 
## it under the terms of the GNU General Public License as published by 
## the Free Software Foundation; either version 2 of the License, or    
## (at your option) any later version.                                  
##                                                                      
##------------------------------------------------------------------------

. ./config_build
. "$SCRIPTS"/misc/lib/lib_fail

echo
echo "----------------------------------"
echo " Copying USB image scripts to drive "
echo " May need sudo pass ..."
echo "----------------------------------"
echo 

# Is the drive here?
GREPX=`mount | grep $DDEV`

if [ x"$GREPX" == x"" ] ; then 
    echo "Mount (insert) $DDEV first."
   	exit
fi

# Is the second drive here?
GREPX=`mount | grep $DDEV2`

if [ x"$GREPX" == x"" ] ; then 
    echo "Mount (insert) $DDEV2 first."
   	exit
fi

CCC=$MCOMBOOT/home/user/comlin-sys/

echo "Copying ComLin scripts to $CCC ... "

sudo mkdir -p $CCC

sudo cp -a *  $CCC
sudo cp -a scripts/  $CCC
sudo cp -a syslinux/  $CCC

# Get UIDS from live target
UUU=`grep ^user: $MCOMBOOT/etc/passwd | awk -F ":" {'print $3'}`
GGG=`grep ^user: $MCOMBOOT/etc/group | awk -F ":" {'print $3'}`

sudo chown -R $UUU.$GGG $CCC

echo Done.
sync

