#!/bin/bash
##########################################################################
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

# Tue 20.May.2025 fixed it in the -- lite -- dir

#echo -n "Patching shutdown files ... "

#FILES="shutdown reboot flushall"
#for aa in $FILES ; do
#    #echo "rm: $aa"
#    rm  -f $ROOTFS/sbin/$aa
#done

#for bb in $FILES ; do
#    #echo "cp: $bb"
#    cp -a shutdown/$bb.sh $ROOTFS/sbin/$bb
#    chown root.root $ROOTFS/sbin/$bb
#    chmod a+x $ROOTFS/sbin/$bb
#    chmod u+s $ROOTFS/sbin/$bb
#done

# Trig anals are symlinks -- nuke them
#rm -f $ROOTFS/sbin/shutdown
#rm -f $ROOTFS/sbin/reboot

#cp -a apps/empty/empty $ROOTFS/sbin/
#cp -a shutdown/. $ROOTFS/sbin/

#echo " OK"

# EOF
