#!/bin/sh
##------------------------------------------------------------------------
##                              
## Cleans local USB image from pipes sockets
##                                                                      
## This program is free software; you can redistribute it and/or modify 
## it under the terms of the GNU General Public License as published by 
## the Free Software Foundation; either version 2 of the License, or    
## (at your option) any later version.                                  
##                                                                      
##------------------------------------------------------------------------

. ./config_build  nocheck
. "$SCRIPTS"/misc/lib/lib_fail

TARG=/media/COMBOOT
MCOMBOOT=/media/COMBOOT

echo
echo "----------------------------------"
echo " Clean USB image from sockets "
echo " May need sudo pass ..."
echo "----------------------------------"
echo 

find $CURRUSB -type s -exec rm -v {} \;
find $CURRUSB -type p -exec rm -v {} \;

sync


