#!/bin/bash
##########################################################################
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. ./config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

#echo
#echo "----------------------------------"
#echo "           Cleaning temps         "
#echo "        May need sudo pass        "
#echo "----------------------------------"
#echo

echo -n "Cleaning DATA ... "

#echo  -rf "$WORK/*"
#echo  -rf "$KERNELDIR/*"
#echo  -rf "$ROOTFS/*"

#rm -rf $KERNELDIR/*
rm -rf $WORK/*
rm -rf $ROOTFS/*

rm -f $TMPDIR/*  >/dev/null 2>&1
rm -f $BACKUPDIR/*  >/dev/null 2>&1

rm -rf $ROOTUSERDIR/.cache  >/dev/null 2>&1

echo OK

#sudo umount "$MOUNTPOINT" > /dev/null 2>&1
#exit 0

# EOF
