#!/bin/bash

. ./config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

#echo "-------------------------------------"
#echo " Get apps into new image "
#echo "-------------------------------------"

if [ ! -f $KEYGET ] ; then
    echo "Please exceute 'make apps' first."
    exit 1;
fi

cpchown() {

    if [ ! -d $2 ] ; then
        mkdir -p $2
    fi
    cp -a $1 $2
    FFF=$2/$(basename $1)
    sudo chown root.root $FFF
    sudo chmod go-w  $FFF
}

TARG=$LITEUSB/usr/bin

echo -n "Copying APPS to $TARG ... "

cpchown $APPDIR/keyget/keyget $TARG
cpchown $APPDIR/keyget/keypeek $TARG

cpchown $APPDIR/reboot/linux_reboot $TARG
cpchown $APPDIR/reboot/linux_poweroff $TARG

cpchown $APPDIR/power/sendacpi $TARG
cpchown $APPDIR/power/powacpi $TARG
cpchown $APPDIR/power/powbutt.sh $TARG
cpchown $APPDIR/power/powbutt.py $TARG
cpchown $APPDIR/power/ctrl_alt_del.py $TARG

cpchown $APPDIR/MessageBox-X11/progress $TARG

cpchown $APPDIR/pypass/passcheck $TARG
cpchown $APPDIR/pypass/pypass.py $TARG
cpchown $APPDIR/pypass/pypass.conf $ROOTFS/etc/pypass

cpchown $APPDIR/pypass/Utils/background.png $ROOTFS/root/Utils
cpchown $APPDIR/pypass/Utils/icon.png $ROOTFS/root/Utils

TARG2=$LITEUSB/usr/local/bin
mkdir -p $TARG2
chown root.root $TARG2

mkdir -p $TARG2/panglib
chown root.root $TARG2/panglib

cpchown ../../../pgpygtk/pangview/pangview.py $TARG2
cp -a ../../../pgpygtk/pangview/panglib/* $TARG2/panglib

echo OK

# EOF
