#!/bin/bash

. ./config_build
. "$SCRIPTS"/misc/lib/lib_fail

echo
echo "-------------------------------------"
echo " Getting new kernel from SYS SRC dir "
echo "--------------------------------------"
echo 

# Copy kernel files from runtime 
# Enable this if you do not have sources and disable the source part below.

#cp -v /vmlinuz _kernel/vmlinuz
#cp -v /boot/System.map*  _kernel/System.map

echo -n "Getting kernel and kernel map ... "

# Copy kernel files from source
sudo cp  /lib/modules/`uname -r`/build/arch/x86/boot/bzImage _kernel/vmlinuz
sudo cp  /lib/modules/`uname -r`/build/System.map _kernel

echo OK

