#!/bin/bash
##########################################################################
##                                                                      ##
## Make the install ISO                                                 ##
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

echo "Preparing ISO image ;"

# See if conditions are met

if [ ! -f $KEYGET ] ; then
    #echo "Must have apps / scripts built first (missing keyget)"
    echo "Execute 'make apps' first."
    exit 1
fi

if [ ! -f $KERNELDIR/$KERNELBIN ] ; then
    echo "Execute 'make getkern' first."
    exit 1
fi

if [ ! -f $KERNELDIR/initramfs ] ; then
    echo "Execute 'make initramfs' first."
    exit 1
fi

echo "Copying (updating) filesystem ... "
#cp -au $CURRUSB/* $ROOTFS

EXC=$(basename $CURRUSB)

rsync -au   --info=progress2 \
            --exclude=/proc/* \
            --exclude=/dev/* \
            --exclude=/sys/* \
            --exclude=/tmp/* \
            --exclude=/run/* \
            $CURRUSB/* $ROOTFS

# Remove incidentals (created during testing)
for aa in "root user guest" ; do
    #echo $aa
    rm -f "$ROOTFS/$aa/.bash_history"
    rm -rf "$ROOTFS/$aa/.config/xfce4"
    rm -rf "$ROOTFS/$aa/tmp"
done

#echo -n "Copying modules ... "
#cp -au $MODULEDIR/* $ROOTFS/lib/modules
#echo OK

echo -n "Copying boot items ... "
cp -a $BOOTDIR/* $ROOTFS/boot
echo OK

echo -n "Copying kernel items ... "
cp -a $KERNELDIR/* $ROOTFS/boot
echo OK

echo -n "Copying shell utilities ... "
cp -a $SHLIB $ROOTFS/lib
echo OK

echo -n "Copying sbin inits ... "
cp -au $INITDIR/* $ROOTFS/sbin
echo OK

echo -n "Copying dev files ... "
mkdir -p $ROOTFS/dev
cp -a $DEVDIR/* $ROOTFS/dev
echo OK

#echo -n "Patching tmp and var permissions ... "
rm -rf $ROOTFS/tmp/
mkdir -p $ROOTFS/tmp
chmod a+rwxt $ROOTFS/tmp

#rm -rf $ROOTFS/var/run/* >/dev/null 2>&1

#echo -n "Patch ICEauthority ... "
echo "" > $ROOTFS/root/.ICEauthority
#echo OK

# Pivot (or equivalent) needs this
mkdir -p $ROOTFS/var/oldroot

# Our ID file
cp $COMLINVERFILE $ROOTFS/etc/COMLINUX_VERSION

# EOF
