#!/bin/sh

. config_build
. "$SCRIPTS"/misc/lib/lib_fail

if [ "$CRAMFS" != "yes" ]; then
	exit 0
fi

if [ "$COMPRESSEDFS" = "yes" ]; then
	echo "Only one of COMPRESSEDFS and CRAMFS can be set to yes." 
	fail
fi

echo "----------------------------------"
echo "     building the cramfs image     "
echo "----------------------------------"
echo 
echo


echo "This can take some time ... "

# first copy the _cd tree to $TMPDIR
mkdir $TMPDIR/_cd           || fail
mkdir $TMPDIR/iso           || fail
mkdir $TMPDIR/iso/boot      || fail
cp -a $ROOTFS/* $TMPDIR/_cd || fail

# delete some files that are already copied to the ramdisk image
rm -rf $TMPDIR/_cd/dev/*         || fail
rm -rf $TMPDIR/_cd/var/*         || fail
rm -rf $TMPDIR/_cd/boot/boot.img || fail

cp $TMPDIR/_cd/README $TMPDIR/iso || fail

# now build the cramfs image file
mkcramfs $TMPDIR/_cd $TMPDIR/iso/boot/rootfs.cramfs.img

mv $ROOTFS/boot/boot.img $TMPDIR/iso/boot/boot.img || fail

mv $ROOTFS $ROOTFS.uncompressed || fail
mv $TMPDIR/iso $ROOTFS          || fail

# clean up
rm -rf $TMPDIR/_cd || fail

echo
