#!/bin/bash
# shellcheck disable=SC2004,SC2009,SC2068,SC2002,SC2086,SC1091
##########################################################################
##                                                                      ##
## Make the install ISO                                                 ##
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

. config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

echo "Preparing ISO image from $CURRUSB ..."

if [ "$ROOTFS" == "" ] ; then
    # This would be really bad;
    echo "Empty ROOTFS variable ... exiting."
    exit 1
fi

# See if conditions are met

if [ ! -f $KEYGET ] ; then
    #echo "Must have apps / scripts built first (missing keyget)"
    echo "Execute 'make apps' first."
    exit 1
fi

if [ ! -f $KERNELDIR/$KERNELBIN ] ; then
    echo "Execute 'make getkern' first."
    exit 1
fi

if [ ! -f $KERNELDIR/initramfs ] ; then
    echo "Execute 'make initramfs' first."
    exit 1
fi

# Pre - Clean some config (to be refilled from target)
rm -f $ROOTFS/usr/share/X11/xorg.conf.d/*

echo "  Copying (updating) filesystem ... "
#cp -au $CURRUSB/* $ROOTFS

#EXC=$(basename $CURRUSB)

#--exclude=/run/* \

rsync -au   --info=progress2 \
            --exclude=/proc/* \
            --exclude=/sys/* \
            --exclude=/tmp/* \
            --exclude=/dev/* \
                $CURRUSB/* $ROOTFS

#echo -n "Copying modules ... "
#cp -au $MODULEDIR/* $ROOTFS/lib/modules
#echo OK

echo -n "  Copying boot items ... "
cp -a $BOOTDIR/* $ROOTFS/boot
echo OK

echo -n "  Copying kernel items ... "
cp -a $KERNELDIR/* $ROOTFS/boot
echo OK

echo -n "  Copying sbin inits ... "

cp -a $INITDIR/* $ROOTFS/sbin
chown root.root $ROOTFS/sbin/*

echo OK

echo -n "  Copying shell utilities ... "
cp -a $SHLIB $ROOTFS/lib
chown root.root $ROOTFS/lib/*
echo OK

echo -n "  Copying dev files ... "
mkdir -p $ROOTFS/dev
cp -a $DEVDIR/* $ROOTFS/dev
echo OK

echo -n "  Copying user files ... "
mkdir -p $ROOTFS/home/user
mkdir -p $ROOTFS/home/guest
mkdir -p $ROOTFS/root
echo OK

echo -n "  Changing user file permissions ... "
cp -a $USERDIR/. $ROOTFS/home/user
UIDX=$(grep user:x etc-dir/passwd  | awk -F ":" '{print $3}')
GIDX=$(grep user:x etc-dir/passwd  | awk -F ":" '{print $4}')
chown -R $UIDX.$GIDX $ROOTFS/home/user/.

cp -a $GUESTDIR/. $ROOTFS/home/guest
UIDG=$(grep guest:x etc-dir/passwd  | awk -F ":" '{print $3}')
GIDG=$(grep guest:x etc-dir/passwd  | awk -F ":" '{print $4}')
chown -R $UIDG.$GIDG $ROOTFS/home/guest/.

cp -a $ROOTUSERDIR/. $ROOTFS/root
UIDR=$(grep root:x etc-dir/passwd  | awk -F ":" '{print $3}')
GIDR=$(grep root:x etc-dir/passwd  | awk -F ":" '{print $4}')
chown -R $UIDR.$GIDR $ROOTFS/root/.

unset UIDX GIDX UIDG GIDG UIDR GIDR
echo OK

# Single user, needs permission
chmod u+s $ROOTFS/bin/chvt

echo -n "  Copying etc files ... "

# The pre created pass and group
cp -a $ETCDIR/* $ROOTFS/etc
chown -R root.root $ROOTFS/etc/*

# XFCE related
cp -a X11/* $ROOTFS/etc/X11
cp -a backgrounds/ $ROOTFS/usr/share/

echo OK

# Remove incidentals (created during testing)
IFS=$' \t\n'        # Restore original IFS
VALS="root home/user home/guest"
for aaa in $VALS ; do
    #echo "Cleaning: $aaa"
    rm -f  "$ROOTFS/$aaa/.sudo_as_admin_successful"
    rm -f  "$ROOTFS/$aaa/.bash_history"
    rm -f  "$ROOTFS/$aaa/.ICEauthority"
    rm -f  "$ROOTFS/$aaa/.Xauthority"
    rm -f  "$ROOTFS/$aaa/.pulse*"
    rm -rf "$ROOTFS/$aaa/.mozilla"
    rm -rf "$ROOTFS/$aaa/.thunderbird"
    rm -rf "$ROOTFS/$aaa/.pyedpro"
    rm -rf "$ROOTFS/$aaa/.config"
    rm -rf "$ROOTFS/$aaa/.local"
    rm -rf "$ROOTFS/$aaa/.cache"
    rm -rf "$ROOTFS/$aaa/.xfce_err"
    rm -rf "$ROOTFS/$aaa/.xfce_out"
    rm -rf "$ROOTFS/$aaa/.xfce*"
    rm -rf "$ROOTFS/$aaa/tmp"
done

echo -n "  Patching tmp and var/tmp permissions ... "
rm -rf $ROOTFS/tmp
mkdir -p $ROOTFS/tmp
chmod a+rwxt $ROOTFS/tmp

rm -rf $ROOTFS/var/tmp
mkdir -p $ROOTFS/var/tmp
chmod a+rwxt $ROOTFS/var/tmp

#rm -rf $ROOTFS/var/run/* >/dev/null 2>&1
rm  -f  $ROOTFS/var/lib/alsa/* >/dev/null 2>&1

echo OK

# Pivot (or equivalent) needs this
mkdir -p $ROOTFS/var/oldroot

# Our ID file
cp $COMLINVERFILE $ROOTFS/etc/COMLINUX_VERSION

# Patch sound devices (done dynamically on init, just clear it)
mkdir -p $ROOTFS/dev/snd
rm -rf $ROOTFS/dev/snd/*

echo "Done prepping ISO."

# EOF
