#!/bin/bash
##########################################################################
##                                                                      ##
## This program is free software; you can redistribute it and/or modify ##
## it under the terms of the GNU General Public License as published by ##
## the Free Software Foundation; either version 2 of the License, or    ##
## (at your option) any later version.                                  ##
##                                                                      ##
##########################################################################

.  config_build nocheck
. "$SCRIPTS"/misc/lib/lib_fail

# This is just a rough check, will only catch syntax errors.

echo -n "Checking scripts ... "

for FF in initramfs/lib/shlib/*.sh ; do
    #echo checking $FF
    bash -n $FF; ERR=$?
    if [ "$ERR" != "0" ] ; then
        echo "Syntax error in $FF"
        exit 1
    fi
done

bash -n initramfs/init; ERR=$?
if [ "$ERR" != "0" ] ; then
    echo "Syntax error in initramfs/init"
    exit 1
fi

bash -n preinit/preinit; ERR=$?
if [ "$ERR" != "0" ] ; then
    echo "Syntax error in preinit/preinit"
    exit 1
fi

bash -n preinit/preinit.sh ; ERR=$?
if [ "$ERR" != "0" ] ; then
    echo "Syntax error in preinit/preinit.sh"
    exit 1
fi

bash -n preinit/postinit ; ERR=$?
if [ "$ERR" != "0" ] ; then
    echo "Syntax error in preinit/postinit"
    exit 1
fi

bash -n preinit/terminit.sh ; ERR=$?
if [ "$ERR" != "0" ] ; then
    echo "Syntax error in preinit/terminit.sh"
    exit 1
fi

shellcheck preinit/*.sh

echo done.

# EOF
