# Makefile

all:
	@echo "Help: make help for more info"

help:
	@echo "Targets: apps help clean"

apps:
	make -C keyget keyget
	make -C reboot
	make -C MessageBox-X11

clean:
	make -C keyget clean
	make -C reboot clean

# EOF
