#
# We created two excutables, following Linux tradition. In the origianl
# implementation, these are symlinks to one excutable, but we are keeping it simple.
#

all: eatzomb

eatzomb: eatzomb.c
	gcc eatzomb.c -o eatzomb

